FROM	python:3.11.4-slim-buster

WORKDIR	/usr/src/app

COPY	./requirements.txt ./

RUN		pip install --no-cache -r requirements.txt

COPY	./ ./

EXPOSE	8001

CMD 	["daphne", "-e", "ssl:8001:privateKey=/etc/ssl/private/server.key:certKey=/etc/ssl/certs/server.crt", "mainProject.asgi:application"]