FROM	python:3.10
EXPOSE	8000
WORKDIR	/usr/src/app

COPY	./requirements.txt ./

RUN		pip install --upgrade pip
RUN		pip install --no-cache -r requirements.txt

COPY	./ ./

RUN		python manage.py makemigrations --noinput

CMD		["sh", "-c", "python manage.py makemigrations mainApp && python manage.py migrate && python manage.py collectstatic --noinput && python manage.py runserver 0.0.0.0:8000 && python manage.py set_all_users_offline"]
