FROM	python:3.8
EXPOSE	8000
WORKDIR	/usr/src/app

COPY	./requirements.txt ./

RUN		pip install --upgrade pip
RUN		pip install --no-cache -r requirements.txt

COPY	./ ./

RUN		python manage.py makemigrations --noinput

CMD 	["sh", "-c", "python manage.py makemigrations mainApp & python manage.py migrate && python manage.py runserver --insecure 0.0.0.0:8000"]

# NOTE BY LEON:
# The --insecure flag is used to serve static file in production.
# It's not insecure, it's just Django who doesn't want to serve static files by default in production.
# See the official documentation for more informations...