FROM	python:3.8
EXPOSE	8001
WORKDIR	/usr/src/app

COPY	./requirements.txt ./

RUN		pip install --no-cache -r requirements.txt

COPY	./ ./

# RUN		openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
# 		-keyout /etc/ssl/private/server.key -out /etc/ssl/certs/server.crt \
# 		-subj "/C=FR/L=Lyon/O=42/OU=ezanotti/CN=ezanotti.42.fr"

COPY	./ssl/server.crt server.crt
COPY	./ssl/server.key server.key

CMD 	["daphne", "-u", "daphne", "-e", "ssl:8001:privateKey=server.key:certKey=server.crt", "pong_game.asgi:application"]