FROM	python:3.8
EXPOSE	8000
WORKDIR	/usr/src/app

COPY	./requirements.txt ./

RUN		pip install --upgrade pip
RUN		pip install --no-cache -r requirements.txt

COPY	./ ./

RUN		mkdir -p ./users_app/profile_pics
COPY	./users_app/profile_pics/default.jpg ./users_app/profile_pics/default.jpg

RUN		pip install requests

RUN		python manage.py makemigrations --noinput

CMD 	["sh", "-c", "python manage.py migrate && python manage.py migrate users_app && python manage.py runserver 0.0.0.0:8000"]
