FROM	python:3.8
EXPOSE	8001
WORKDIR	/usr/src/app

COPY	./requirements.txt ./

RUN		pip install --no-cache -r requirements.txt

COPY	./ ./

CMD 	["daphne", "-e", "ssl:8001:privateKey=/etc/ssl/private/server.key:certKey=/etc/ssl/certs/server.crt", "main.asgi:application"]