FROM python:3.8

WORKDIR /usr/src/app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY ./pong_game/ ./

CMD ["daphne", "-u", "/tmp/daphne.sock", "pong_game.asgi:application", "-p", "8000"]