FROM python:3.8

WORKDIR /usr/src/app

COPY ./requirements.txt ./

RUN pip install --no-cache -r requirements.txt

COPY . .

EXPOSE 8001

# TODO peutetre pong_app
CMD ["daphne", "-u", "daphne.sock", "pong_game.asgi:application"]