FROM	python:3.8
EXPOSE	8001
WORKDIR	/usr/src/app

COPY	./requirements.txt ./

RUN		pip install --no-cache -r requirements.txt

COPY	./ ./

CMD		["daphne", "-u", "daphne.sock", "pong_game.asgi:application"]