FROM python:3.8

WORKDIR /usr/src/app

COPY ./requirements.txt ./

RUN pip install --no-cache -r requirements.txt

COPY . .

# TODO a fix
# RUN python manage.py makemigrations --noinput
# RUN python manage.py migrate --noinput

EXPOSE 8000

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]